FROM openjdk:17-alpine AS builder

COPY ./mvnw .
COPY ./pom.xml .
COPY ./src src
COPY ./rest.iml .
RUN chmod +x mvnw

#RUN ./mvnw clean package
FROM openjdk:17-alpine

COPY target/cuvariPasa.jar /app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app.jar"]